"""Constrained / structured decoding via logit masking.

The reliability lever for tool calls and JSON mode (Frontier + System Design
manuals): instead of *hoping* the model emits valid output and re-prompting on
failure, we **make invalid output impossible**. At every decode step a
``Constraint`` declares which token ids are still legal given what has been
generated so far; every other logit is forced to ``-inf`` before sampling. The
model can only ever walk paths the grammar allows. This is the idea behind
guided / grammar-constrained decoding (xgrammar, Outlines, llama.cpp GBNF,
OpenAI structured outputs): correctness comes from the *decoder*, not from the
weights, so it works even on a tiny untrained model.

Two constraints are implemented:

  * ``ChoiceConstraint`` - output must be exactly one of a fixed list of strings.
    We track, byte-for-byte, which options are still reachable and mask to only
    the tokens that extend some still-viable option. Once exactly one option is
    fully matched we stop. This GUARANTEES the output is one of the choices.

  * ``JSONConstraint`` - a small hand-written state machine that constrains output
    toward a simple JSON-object shape, e.g. ``{"tool": "...", "args": {...}}``.
    It is a *simplified* grammar (see "Limitations" below), not a full JSON
    parser; the goal is structurally valid-ish, parseable-enough output, which is
    exactly what a downstream ``parse_tool_call`` needs.

Limitations (JSONConstraint): we constrain structural punctuation (braces,
quotes, colons, commas) and a permissive byte set inside string values, but we do
not validate that string contents are semantically meaningful, do not handle
nested objects beyond one ``args`` level, do not enforce numbers/booleans, and do
not handle escape sequences inside strings. It is a teaching-grade grammar, not a
spec-complete JSON validator. For production use a real grammar engine.

Token-level masking caveat: a BPE tokenizer can merge several characters into one
token, so a single token may carry text that overshoots a grammar boundary (e.g.
a token that is ``"}`` together). We handle this by working at the *byte* level:
for each candidate next token we ask "does appending this token's bytes keep the
output on a legal path?" and mask out tokens whose bytes would violate the
grammar. This is exact for the prefixes we care about and avoids depending on the
tokenizer's particular merge table.
"""
from __future__ import annotations

import json
from typing import Iterable, Protocol

import torch

from ..data.tokenizer import BPETokenizer
from ..model.transformer import KVCache


# --------------------------------------------------------------------------- #
# Constraint interface
# --------------------------------------------------------------------------- #
class Constraint(Protocol):
    """A constraint maps the tokens generated so far to the set of legal next
    tokens. Returning ``None`` means "all tokens allowed" (no constraint)."""

    def allowed_token_ids(self, generated_ids: list[int]) -> "set[int] | None":
        ...

    def is_complete(self, generated_ids: list[int]) -> bool:
        """Whether the constrained string is finished (decode may stop early)."""
        ...


def _decoded_bytes(tok: BPETokenizer, ids: Iterable[int]) -> bytes:
    """Concatenate the raw bytes a list of (non-special) token ids decodes to.

    We deliberately use the vocab byte table rather than ``decode`` (which
    UTF-8-decodes with replacement) so byte-level prefix checks are exact.
    """
    out = bytearray()
    for i in ids:
        if i in tok.id_to_special:
            out.extend(tok.id_to_special[i].encode("utf-8"))
        else:
            out.extend(tok.vocab.get(i, b""))
    return bytes(out)


def _token_bytes_map(tok: BPETokenizer) -> dict[int, bytes]:
    """id -> bytes for every ordinary (non-special) vocab entry."""
    return {i: b for i, b in tok.vocab.items() if i not in tok.id_to_special}


# --------------------------------------------------------------------------- #
# ChoiceConstraint: output must be exactly one of a fixed set of strings
# --------------------------------------------------------------------------- #
class ChoiceConstraint:
    """Force the output to be exactly one of ``options``.

    State is derived purely from the bytes generated so far: an option is still
    *viable* if the generated bytes are a prefix of (or equal to) that option's
    bytes. A token is allowed if appending its bytes keeps the generation a
    prefix of at least one still-viable option. The constraint is complete once
    the generated bytes exactly equal one of the options.
    """

    def __init__(self, options: list[str], tok: BPETokenizer):
        if not options:
            raise ValueError("ChoiceConstraint needs at least one option")
        self.tok = tok
        self.option_bytes = [o.encode("utf-8") for o in options]
        self._tok_bytes = _token_bytes_map(tok)

    def _gen_bytes(self, generated_ids: list[int]) -> bytes:
        return _decoded_bytes(self.tok, generated_ids)

    def allowed_token_ids(self, generated_ids: list[int]) -> "set[int] | None":
        cur = self._gen_bytes(generated_ids)
        viable = [o for o in self.option_bytes if o.startswith(cur)]
        if not viable:
            return set()  # dead end; nothing legal (shouldn't happen if we drive it)
        allowed: set[int] = set()
        for tid, tb in self._tok_bytes.items():
            if not tb:
                continue
            nxt = cur + tb
            # legal if nxt is a prefix of some option (it can still grow into it)
            if any(o.startswith(nxt) for o in viable):
                allowed.add(tid)
        return allowed

    def is_complete(self, generated_ids: list[int]) -> bool:
        cur = self._gen_bytes(generated_ids)
        return cur in self.option_bytes


# --------------------------------------------------------------------------- #
# JSONConstraint: a tiny state machine for {"tool": "...", "args": {...}}
# --------------------------------------------------------------------------- #
# We define a fixed key skeleton and constrain structural characters exactly,
# while allowing a permissive byte set inside quoted string values. The "args"
# value is constrained to a flat object of "key": "value" pairs.
#
# Grammar (informal):
#   doc   := '{' '"tool"' ':' STR ',' '"args"' ':' OBJ '}'
#   OBJ   := '{' (PAIR (',' PAIR)*)? '}'
#   PAIR  := STR ':' STR
#   STR   := '"' SCHAR* '"'
#   SCHAR := any byte except '"' and '\' and control chars
#
# Implemented as an explicit byte-driven walker so we never depend on token
# boundaries: from the bytes emitted so far we compute the set of *legal next
# bytes*, then allow exactly the tokens whose full byte string keeps us legal.
class JSONConstraint:
    """Constrain output toward ``{"tool": "<str>", "args": {<pairs>}}``.

    Simplified grammar; see module docstring for limitations. Robust enough that
    the emitted text round-trips through ``json.loads`` for the shapes it allows.
    """

    _STRUCT = b'{}":,'  # structural characters we mint exactly

    def __init__(self, tok: BPETokenizer, *, max_str_len: int = 24):
        self.tok = tok
        self._tok_bytes = _token_bytes_map(tok)
        self.max_str_len = max_str_len

    # ---- byte-level legality oracle ---------------------------------- #
    def _legal_next_bytes(self, s: bytes) -> "set[int] | None":
        """Given the JSON bytes emitted so far, return the set of legal next
        byte values (as ints 0..255), or None if the document is complete."""
        # The target skeleton, tokenised into literal segments and free fields.
        # We walk it with a tiny cursor over ``s``.
        target = b'{"tool":'
        # Phase 1: emit the fixed opening literal '{"tool":'
        if len(s) < len(target):
            # still typing the fixed prefix
            return {target[len(s)]}
        rest = s[len(target):]

        # Phase 2: a quoted tool string value
        consumed, done = self._match_string(rest)
        if not done:
            return self._string_next_bytes(rest)
        rest = rest[consumed:]

        # Phase 3: the fixed middle literal ',"args":{'
        mid = b',"args":{'
        if len(rest) < len(mid):
            return {mid[len(rest)]}
        rest = rest[len(mid):]

        # Phase 4: zero or more "key":"value" pairs, then a closing '}' then '}'
        return self._object_body_next(rest)

    # ---- helpers ----------------------------------------------------- #
    @staticmethod
    def _is_schar(b: int) -> bool:
        # printable ASCII minus '"' (34) and '\' (92)
        return 32 <= b < 127 and b != 34 and b != 92

    def _string_next_bytes(self, s: bytes) -> set[int]:
        """Legal next bytes while we are inside / about to start a string."""
        if not s:
            return {34}  # must open with a quote
        if s[0] != 34:
            return {34}
        body = s[1:]
        # if body already contains a closing quote we're past the string
        if 34 in body:
            return set()
        opts = {b for b in range(256) if self._is_schar(b)}
        # allow closing quote unless empty-and-we-want-content? allow empty too
        opts.add(34)
        if len(body) >= self.max_str_len:
            return {34}  # force-close overly long strings
        return opts

    def _match_string(self, s: bytes) -> tuple[int, bool]:
        """Try to consume a complete quoted string at the start of ``s``.
        Returns (bytes_consumed, complete?)."""
        if not s or s[0] != 34:
            return 0, False
        for i in range(1, len(s)):
            if s[i] == 34:
                return i + 1, True
        return len(s), False  # open string, not yet closed

    def _object_body_next(self, s: bytes) -> "set[int] | None":
        """Walk the flat args object body (already past the opening '{')."""
        # Empty object can close immediately.
        if s == b"":
            return {ord("}"), ord('"')}
        # Walk pairs.
        i = 0
        n = len(s)
        while i < n:
            # Expect a key string.
            consumed, done = self._match_string(s[i:])
            if not done:
                return self._string_next_bytes(s[i:])
            i += consumed
            # Expect ':'
            if i >= n:
                return {ord(":")}
            if s[i:i + 1] != b":":
                return {ord(":")}
            i += 1
            # Expect a value string.
            consumed, done = self._match_string(s[i:])
            if not done:
                return self._string_next_bytes(s[i:])
            i += consumed
            # After a pair: either ',' (another pair) or '}' (close args).
            if i >= n:
                return {ord(","), ord("}")}
            c = s[i:i + 1]
            if c == b",":
                i += 1
                # after comma a new key must start
                if i >= n:
                    return {ord('"')}
                continue
            if c == b"}":
                i += 1
                # args object closed; now the outer doc must close with '}'
                if i >= n:
                    return {ord("}")}
                if s[i:i + 1] == b"}":
                    return None  # document complete
                return {ord("}")}
            return {ord(","), ord("}")}
        # Fell through: we're mid-structure, default to closing options.
        return {ord("}"), ord('"'), ord(",")}

    # ---- Constraint interface ---------------------------------------- #
    def allowed_token_ids(self, generated_ids: list[int]) -> "set[int] | None":
        s = _decoded_bytes(self.tok, generated_ids)
        if self._legal_next_bytes(s) is None:
            return set()  # complete -> no further tokens
        allowed: set[int] = set()
        for tid, tb in self._tok_bytes.items():
            if not tb:
                continue
            if self._token_keeps_legal(s, tb):
                allowed.add(tid)
        return allowed

    def _token_keeps_legal(self, s: bytes, tb: bytes) -> bool:
        """A token is allowed iff every byte it adds is legal at its position."""
        cur = s
        for b in tb:
            legal = self._legal_next_bytes(cur)
            if legal is None:        # already complete -> no more bytes allowed
                return False
            if b not in legal:
                return False
            cur = cur + bytes([b])
        return True

    def is_complete(self, generated_ids: list[int]) -> bool:
        s = _decoded_bytes(self.tok, generated_ids)
        return self._legal_next_bytes(s) is None


# --------------------------------------------------------------------------- #
# Constrained decode loop
# --------------------------------------------------------------------------- #
@torch.no_grad()
def constrained_generate(engine, prompt: str, constraint: Constraint,
                         *, max_new_tokens: int = 64,
                         temperature: float = 0.0) -> str:
    """Greedy/sampled decode that masks disallowed logits to ``-inf`` each step.

    Uses the engine's model + tokenizer + sampler. At every step we ask the
    constraint which token ids are legal, set all others to ``-inf``, then let
    the engine's ``_sample`` pick among the survivors. Stops when the constraint
    reports completion (or on ``<eos>`` / ``max_new_tokens``).
    """
    model = engine.model
    tok = engine.tok
    device = engine.device
    eos = tok.id("<eos>")
    max_ctx = engine.cfg.model.max_seq_len

    prompt_ids = engine._format_prompt(prompt)
    cache = KVCache(len(model.blocks))
    ids = torch.tensor([prompt_ids[-max_ctx:]], dtype=torch.long, device=device)
    logits, _ = model(ids, cache=cache, start_pos=0)
    pos = ids.size(1)

    generated: list[int] = []
    for _ in range(max_new_tokens):
        if constraint.is_complete(generated):
            break
        row = logits[0, -1].float().clone()
        allowed = constraint.allowed_token_ids(generated)
        if allowed is not None:
            if not allowed:
                break  # constraint says nothing legal -> stop
            mask = torch.full_like(row, float("-inf"))
            idx = torch.tensor(sorted(allowed), dtype=torch.long, device=row.device)
            mask[idx] = row[idx]
            row = mask
        nxt = engine._sample(row, generated, temperature, 0, 1.0, 1.0)
        if nxt == eos:
            break
        generated.append(nxt)
        cur = torch.tensor([[nxt]], dtype=torch.long, device=device)
        logits, _ = model(cur, cache=cache, start_pos=pos)
        pos += 1

    return tok.decode(generated)


# --------------------------------------------------------------------------- #
# Self-test
# --------------------------------------------------------------------------- #
if __name__ == "__main__":
    from ..config import get_config
    from ..inference.engine import InferenceEngine
    from ..model.transformer import LyceumLM

    cfg = get_config("nano")
    tok = BPETokenizer(special_tokens=cfg.tokenizer.special_tokens)
    tok.train(
        'the quick brown fox. {"tool": "calculator", "args": {"x": "1"}} '
        "weather search calculator email " * 30,
        vocab_size=400,
    )
    model = LyceumLM(cfg.model, vocab_size=tok.vocab_size).eval()
    eng = InferenceEngine(model, tok, cfg)

    print("== ChoiceConstraint ==")
    options = ["calculator", "weather", "search"]
    cc = ChoiceConstraint(options, tok)
    seen = set()
    # sample a few times under temperature to exercise different paths
    for temp in (0.0, 1.0, 1.5, 2.0):
        out = constrained_generate(eng, "pick a tool:", cc,
                                    max_new_tokens=32, temperature=temp)
        assert out in options, f"ChoiceConstraint produced {out!r} not in {options}"
        seen.add(out)
        print(f"  temp={temp}: -> {out!r}  (in options: True)")
    print(f"  distinct options reached: {sorted(seen)}")

    print("\n== JSONConstraint ==")
    jc = JSONConstraint(tok, max_str_len=12)
    ok_count = 0
    for temp in (0.0, 1.0, 2.0):
        out = constrained_generate(eng, "emit a tool call:", jc,
                                    max_new_tokens=96, temperature=temp)
        parseable = False
        try:
            obj = json.loads(out)
            parseable = isinstance(obj, dict) and "tool" in obj and "args" in obj
        except Exception:
            parseable = False
        ok_count += int(parseable)
        print(f"  temp={temp}: {out!r}  parseable={parseable}")
    assert ok_count >= 1, "JSONConstraint never produced parseable JSON"
    print(f"  parseable outputs: {ok_count}/3")

    print("\nself-test OK: ChoiceConstraint always in-options; JSON parseable.")
